// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1SttrqEZs6NZGi1FDsMYdWrGWjZyPSbA',
    appId: '1:88356992647:web:6c681248b546d62660aa22',
    messagingSenderId: '88356992647',
    projectId: 'rpgtaskmanagement',
    authDomain: 'rpgtaskmanagement.firebaseapp.com',
    storageBucket: 'rpgtaskmanagement.firebasestorage.app',
    measurementId: 'G-4NHTGX8HLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOb-1Q0kABzyT2y7Y5fokXBAal-hsPpYI',
    appId: '1:88356992647:android:46ecac909b3ec90c60aa22',
    messagingSenderId: '88356992647',
    projectId: 'rpgtaskmanagement',
    storageBucket: 'rpgtaskmanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-2Pqm-eXNSl9ZPYQqkGYVKuYhoupPRx4',
    appId: '1:88356992647:ios:0ad010185d5dc54260aa22',
    messagingSenderId: '88356992647',
    projectId: 'rpgtaskmanagement',
    storageBucket: 'rpgtaskmanagement.firebasestorage.app',
    iosBundleId: 'com.example.taskun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-2Pqm-eXNSl9ZPYQqkGYVKuYhoupPRx4',
    appId: '1:88356992647:ios:0ad010185d5dc54260aa22',
    messagingSenderId: '88356992647',
    projectId: 'rpgtaskmanagement',
    storageBucket: 'rpgtaskmanagement.firebasestorage.app',
    iosBundleId: 'com.example.taskun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1SttrqEZs6NZGi1FDsMYdWrGWjZyPSbA',
    appId: '1:88356992647:web:c3808ccf8d97948e60aa22',
    messagingSenderId: '88356992647',
    projectId: 'rpgtaskmanagement',
    authDomain: 'rpgtaskmanagement.firebaseapp.com',
    storageBucket: 'rpgtaskmanagement.firebasestorage.app',
    measurementId: 'G-5R8Y5WKZJZ',
  );

}